// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.chalabi.EtudeDeCas.stubs;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chalabi.EtudeDeCas.Empty)
    com.google.protobuf.MessageOrBuilder {
}
