// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.chalabi.EtudeDeCas.stubs;

public interface GetReservationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chalabi.EtudeDeCas.GetReservationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
