// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.chalabi.EtudeDeCas.stubs;

public interface ReservationListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chalabi.EtudeDeCas.ReservationList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.chalabi.EtudeDeCas.Reservation reservations = 1;</code>
   */
  java.util.List<com.chalabi.EtudeDeCas.stubs.Reservation> 
      getReservationsList();
  /**
   * <code>repeated .com.chalabi.EtudeDeCas.Reservation reservations = 1;</code>
   */
  com.chalabi.EtudeDeCas.stubs.Reservation getReservations(int index);
  /**
   * <code>repeated .com.chalabi.EtudeDeCas.Reservation reservations = 1;</code>
   */
  int getReservationsCount();
  /**
   * <code>repeated .com.chalabi.EtudeDeCas.Reservation reservations = 1;</code>
   */
  java.util.List<? extends com.chalabi.EtudeDeCas.stubs.ReservationOrBuilder> 
      getReservationsOrBuilderList();
  /**
   * <code>repeated .com.chalabi.EtudeDeCas.Reservation reservations = 1;</code>
   */
  com.chalabi.EtudeDeCas.stubs.ReservationOrBuilder getReservationsOrBuilder(
      int index);
}
